spring.application.name=LeetcodeTracker

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.file.name=tracker.log


spring.profiles.active=dev